# Generated by Django 2.2.14 on 2020-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('desc', models.TextField()),
                ('comp', models.CharField(max_length=200)),
            ],
        ),
    ]
