# Generated by Django 2.2.14 on 2020-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
